### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [TheRojam/vertepommes-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by TheRojam** [comment]
Thanks for this remark. I'll update the README file and add a screenshot.
But I think you need also oh-my-zsh to run it smoothly.
